### ISSUE TITLE
f-rae train tensor shape error

### ISSUE THREAD

**Issue by andrely** [auDeep/auDeep#28]
### System information
Make sure to provide all system information that may be relevant to the issue you are reporting. Some common points are:

- **Have I written custom code (as opposed to using an example script provided with auDeep)**: Fixed the masked silence and tf.scope issues.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: AWS linux and OSX 10.13
- **auDeep version (Git commit SHA / release version)**: b681188555a95a72e9ee8cf7dfbe9b8a41dae987
- **Python version**: 3.6
- **Exact command to reproduce**:

Features extracted from gtzan using example command in readme.

audeep f-rae train --input features.nc --run-name /opt/ml/model/autoencoder --num-epochs 64 --batch-size 64 --learning-rate 0.001 --freq-window-width 32 --freq-window-overlap 24 --num-layers 2 --num-units 256 --keep-prob 0.8 --encoder-noise 0.0 --feed-previous-prob 0.0 --cell GRU --bidirectional-decoder

### Describe the problem
Describe the problem clearly here. 

Command crashes:

[INFO] TrainFrequencyAutoencoder - created temporary file /tmp/tmpiwqlpap9/features.hdf5-0 for data set /opt/ml/input/data/data/features.hdf5
[INFO] audeep.backend.data.data_set - loading data set from /opt/ml/input/data/data/features.hdf5
[INFO] audeep.backend.data.export - writing data set as TFRecords to /tmp/tmpiwqlpap9/features.hdf5-0
[INFO] FrequencyAutoencoderWrapper - building computation graph
[INFO] GraphWrapper - initializing variables
[INFO] FrequencyAutoencoderWrapper - preparing input queues
[INFO] FrequencyAutoencoderWrapper - preparing input queues
[ERROR] audeep - Input to reshape is a tensor with 8126464 values, but the requested shape has 4063232
#011 [[node model/representation/Reshape (defined at /usr/local/lib/python3.6/site-packages/audeep/backend/training/base.py:328) ]]
#011 [[node model/representation/stddev/Sqrt (defined at /usr/local/lib/python3.6/site-packages/audeep/backend/training/base.py:328) ]]
Caused by op 'model/representation/Reshape', defined at: File "/usr/local/bin/audeep", line 10, in <module> sys.exit(main()) File "/usr/local/lib/python3.6/site-packages/audeep/main.py", line 111, in main return myapp.run(argv) File "/usr/local/lib/python3.6/site-packages/cliff/app.py", line 281, in run result = self.run_subcommand(remainder) File "/usr/local/lib/python3.6/site
InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 8126464 values, but the requested shape has 4063232
#011 [[node model/representation/Reshape (defined at /usr/local/lib/python3.6/site-packages/audeep/backend/training/base.py:328) ]]
#011 [[node model/representation/stddev/Sqrt (defined at /usr/local/lib/python3.6/site-packages/audeep/backend/training/base.py:328) ]]

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. In particular, run commands that produce an error with the `--verbose` and `--debug` flags and attach the output to the issue. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

audeep f-rae train --input audeep-tmp/spectrograms/gtzan-genres-5-0.08-0.04-128-60.nc --run-name audeep-tmp/autoencoder/ --num-epochs 64 --batch-size 64 --learning-rate 0.001 --freq-window-width 32 --freq-window-overlap 24 --num-layers 2 --num-units 256 --keep-prob 0.8 --encoder-noise 0.0 --feed-previous-prob 0.0 --cell GRU --bidirectional-decoder --debug
[INFO] TrainFrequencyAutoencoder - created temporary file /var/folders/05/6qqstxkn04562302q7rkfqmh0000gn/T/tmp07oqewe5/gtzan-genres-5-0.08-0.04-128-60.nc-0 for data set audeep-tmp/spectrograms/gtzan-genres-5-0.08-0.04-128-60.nc
[INFO] audeep.backend.data.data_set - loading data set from audeep-tmp/spectrograms/gtzan-genres-5-0.08-0.04-128-60.nc
[INFO] audeep.backend.data.export - writing data set as TFRecords to /var/folders/05/6qqstxkn04562302q7rkfqmh0000gn/T/tmp07oqewe5/gtzan-genres-5-0.08-0.04-128-60.nc-0
[INFO] FrequencyAutoencoderWrapper - building computation graph
2019-07-30 20:40:04.652162: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[INFO] GraphWrapper - initializing variables
[INFO] FrequencyAutoencoderWrapper - preparing input queues
2019-07-30 20:40:42.764906: W tensorflow/core/kernels/queue_base.cc:277] _1_input_queue/shuffle_batch/random_shuffle_queue: Skipping cancelled enqueue attempt with queue not closed
2019-07-30 20:40:42.765095: W tensorflow/core/kernels/queue_base.cc:277] _1_input_queue/shuffle_batch/random_shuffle_queue: Skipping cancelled enqueue attempt with queue not closed
2019-07-30 20:40:42.765230: W tensorflow/core/kernels/queue_base.cc:277] _0_input_queue/input_producer: Skipping cancelled enqueue attempt with queue not closed
[ERROR] audeep - Input to reshape is a tensor with 8126464 values, but the requested shape has 4063232
	 [[node model/representation/Reshape (defined at /Users/andrelynum/Work/auDeep/audeep/backend/training/base.py:328)  = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](model/representation/Tanh, model/representation/Reshape/shape)]]

Caused by op 'model/representation/Reshape', defined at:
  File "/Users/andrelynum/anaconda3/envs/default/bin/audeep", line 11, in <module>
    load_entry_point('auDeep', 'console_scripts', 'audeep')()
  File "/Users/andrelynum/Work/auDeep/audeep/main.py", line 111, in main
    return myapp.run(argv)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/cliff/app.py", line 281, in run
    result = self.run_subcommand(remainder)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/cliff/app.py", line 401, in run_subcommand
    result = cmd.run(parsed_args)
  File "/Users/andrelynum/Work/auDeep/audeep/cli/train.py", line 187, in run
    retval = super().run(parsed_args)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/cliff/command.py", line 185, in run
    return_code = self.take_action(parsed_args) or 0
  File "/Users/andrelynum/Work/auDeep/audeep/cli/train.py", line 362, in take_action
    decoder_feed_previous_prob=parsed_args.feed_previous_prob)
  File "/Users/andrelynum/Work/auDeep/audeep/backend/training/base.py", line 427, in train_model
    input_map=input_map)
  File "/Users/andrelynum/Work/auDeep/audeep/backend/training/base.py", line 328, in _load_graph
    input_map=input_map)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1674, in import_meta_graph
    meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1696, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py", line 806, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 234, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3440, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3440, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3299, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 8126464 values, but the requested shape has 4063232
	 [[node model/representation/Reshape (defined at /Users/andrelynum/Work/auDeep/audeep/backend/training/base.py:328)  = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](model/representation/Tanh, model/representation/Reshape/shape)]]
Traceback (most recent call last):
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 8126464 values, but the requested shape has 4063232
	 [[{{node model/representation/Reshape}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](model/representation/Tanh, model/representation/Reshape/shape)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/cliff/app.py", line 401, in run_subcommand
    result = cmd.run(parsed_args)
  File "/Users/andrelynum/Work/auDeep/audeep/cli/train.py", line 187, in run
    retval = super().run(parsed_args)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/cliff/command.py", line 185, in run
    return_code = self.take_action(parsed_args) or 0
  File "/Users/andrelynum/Work/auDeep/audeep/cli/train.py", line 362, in take_action
    decoder_feed_previous_prob=parsed_args.feed_previous_prob)
  File "/Users/andrelynum/Work/auDeep/audeep/backend/training/base.py", line 450, in train_model
    _, l, summary = session.run([graph_wrapper.train_op, graph_wrapper.loss, tf_merged_summaries])
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 8126464 values, but the requested shape has 4063232
	 [[node model/representation/Reshape (defined at /Users/andrelynum/Work/auDeep/audeep/backend/training/base.py:328)  = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](model/representation/Tanh, model/representation/Reshape/shape)]]

Caused by op 'model/representation/Reshape', defined at:
  File "/Users/andrelynum/anaconda3/envs/default/bin/audeep", line 11, in <module>
    load_entry_point('auDeep', 'console_scripts', 'audeep')()
  File "/Users/andrelynum/Work/auDeep/audeep/main.py", line 111, in main
    return myapp.run(argv)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/cliff/app.py", line 281, in run
    result = self.run_subcommand(remainder)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/cliff/app.py", line 401, in run_subcommand
    result = cmd.run(parsed_args)
  File "/Users/andrelynum/Work/auDeep/audeep/cli/train.py", line 187, in run
    retval = super().run(parsed_args)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/cliff/command.py", line 185, in run
    return_code = self.take_action(parsed_args) or 0
  File "/Users/andrelynum/Work/auDeep/audeep/cli/train.py", line 362, in take_action
    decoder_feed_previous_prob=parsed_args.feed_previous_prob)
  File "/Users/andrelynum/Work/auDeep/audeep/backend/training/base.py", line 427, in train_model
    input_map=input_map)
  File "/Users/andrelynum/Work/auDeep/audeep/backend/training/base.py", line 328, in _load_graph
    input_map=input_map)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1674, in import_meta_graph
    meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1696, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py", line 806, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 234, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3440, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3440, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3299, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 8126464 values, but the requested shape has 4063232
	 [[node model/representation/Reshape (defined at /Users/andrelynum/Work/auDeep/audeep/backend/training/base.py:328)  = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](model/representation/Tanh, model/representation/Reshape/shape)]]

Traceback (most recent call last):
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 8126464 values, but the requested shape has 4063232
	 [[{{node model/representation/Reshape}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](model/representation/Tanh, model/representation/Reshape/shape)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andrelynum/anaconda3/envs/default/bin/audeep", line 11, in <module>
    load_entry_point('auDeep', 'console_scripts', 'audeep')()
  File "/Users/andrelynum/Work/auDeep/audeep/main.py", line 111, in main
    return myapp.run(argv)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/cliff/app.py", line 281, in run
    result = self.run_subcommand(remainder)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/cliff/app.py", line 401, in run_subcommand
    result = cmd.run(parsed_args)
  File "/Users/andrelynum/Work/auDeep/audeep/cli/train.py", line 187, in run
    retval = super().run(parsed_args)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/cliff/command.py", line 185, in run
    return_code = self.take_action(parsed_args) or 0
  File "/Users/andrelynum/Work/auDeep/audeep/cli/train.py", line 362, in take_action
    decoder_feed_previous_prob=parsed_args.feed_previous_prob)
  File "/Users/andrelynum/Work/auDeep/audeep/backend/training/base.py", line 450, in train_model
    _, l, summary = session.run([graph_wrapper.train_op, graph_wrapper.loss, tf_merged_summaries])
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 8126464 values, but the requested shape has 4063232
	 [[node model/representation/Reshape (defined at /Users/andrelynum/Work/auDeep/audeep/backend/training/base.py:328)  = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](model/representation/Tanh, model/representation/Reshape/shape)]]

Caused by op 'model/representation/Reshape', defined at:
  File "/Users/andrelynum/anaconda3/envs/default/bin/audeep", line 11, in <module>
    load_entry_point('auDeep', 'console_scripts', 'audeep')()
  File "/Users/andrelynum/Work/auDeep/audeep/main.py", line 111, in main
    return myapp.run(argv)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/cliff/app.py", line 281, in run
    result = self.run_subcommand(remainder)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/cliff/app.py", line 401, in run_subcommand
    result = cmd.run(parsed_args)
  File "/Users/andrelynum/Work/auDeep/audeep/cli/train.py", line 187, in run
    retval = super().run(parsed_args)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/cliff/command.py", line 185, in run
    return_code = self.take_action(parsed_args) or 0
  File "/Users/andrelynum/Work/auDeep/audeep/cli/train.py", line 362, in take_action
    decoder_feed_previous_prob=parsed_args.feed_previous_prob)
  File "/Users/andrelynum/Work/auDeep/audeep/backend/training/base.py", line 427, in train_model
    input_map=input_map)
  File "/Users/andrelynum/Work/auDeep/audeep/backend/training/base.py", line 328, in _load_graph
    input_map=input_map)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1674, in import_meta_graph
    meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1696, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py", line 806, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 234, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3440, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3440, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3299, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/Users/andrelynum/anaconda3/envs/default/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 8126464 values, but the requested shape has 4063232
	 [[node model/representation/Reshape (defined at /Users/andrelynum/Work/auDeep/audeep/backend/training/base.py:328)  = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](model/representation/Tanh, model/representation/Reshape/shape)]]

**Comment by Vini1424** [comment]
I have the same issue. Is there any solution for that?
