### ISSUE TITLE
audeep - specified parser is unable to parse data set at test_audio2

### ISSUE THREAD

**Issue by ben-williams-ai** [auDeep/auDeep#43]
### System information
Make sure to provide all system information that may be relevant to the issue you are reporting. Some common points are:

- **OS**: Windows 10
- **auDeep version**: 0.9.6a1
- **Python version**: 3.7
- **Exact command to reproduce**: audeep inspect raw --basedir test_audio2

I get the same issue as #40 when trying to execute `audeep inspect raw --basedir test_audio2` over .wav files. This returns: [ERROR] audeep - specified parser is unable to parse data set at test_audio2

When I use the example ESC-10 dataset, which contains .ogg files, it works fine. If I execute this on a folder with my own data in the .ogg file format it still works fine. But, if I convert the ESC-10 to .wav files or attempt this on my own data which are .wav files, I get this error.

Here is the result when I try to execute this on my own folder with the same directory structure as ESC-10, but with .wav files. I used `--verbose` and `--debug`:

(test-auDeep-env) C:\Users\bw339\OneDrive - University College London\UCL PhD\Chapter One>audeep inspect raw --basedir test_audio2 --verbose --debug
2021-09-01 13:42:56.899808: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2021-09-01 13:42:56.899936: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[DEBUG] audeep - initializing app
[DEBUG] audeep - prepare_to_run_command InspectRaw
[DEBUG] PartitionedParser - cannot parse: there has to be at least one partition directory
[DEBUG] CrossValidatedParser - cannot parse: need at least two fold directories
[DEBUG] ESCParser - cannot parse: unexpected file 2-66660-A.wav in class directory 001 - Dog bark (only *.ogg files allowed)
[DEBUG] UrbanSound8KParser - cannot parse: audio directory at test_audio2\audio missing
[ERROR] audeep - specified parser is unable to parse data set at test_audio2
Traceback (most recent call last):
  File "c:\users\bw339\anaconda3\envs\test-audeep-env\lib\site-packages\cliff\app.py", line 400, in run_subcommand
    result = cmd.run(parsed_args)
  File "c:\users\bw339\anaconda3\envs\test-audeep-env\lib\site-packages\cliff\command.py", line 187, in run
    return_code = self.take_action(parsed_args) or 0
  File "c:\users\bw339\anaconda3\envs\test-audeep-env\lib\site-packages\audeep\cli\inspect.py", line 77, in take_action
    raise ValueError("specified parser is unable to parse data set at {}".format(parsed_args.basedir))
ValueError: specified parser is unable to parse data set at test_audio2
[DEBUG] audeep - clean_up InspectRaw

**Comment by ben-williams-ai** [comment]
Solved by using the parser properly, e,g: `audeep preprocess --basedir test_audio --parser audeep.backend.parsers.no_metadata.NoMetadataParser --window-width 0.08 --window-overlap 0.04 --mel-spectrum 128 --fixed-length 5 --pretend 10`
